/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AjRouteImport } from './routes/aj'
import { Route as IndexRouteImport } from './routes/index'

const AjRoute = AjRouteImport.update({
  id: '/aj',
  path: '/aj',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aj': typeof AjRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aj': typeof AjRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aj': typeof AjRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/aj'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/aj'
  id: '__root__' | '/' | '/aj'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjRoute: typeof AjRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aj': {
      id: '/aj'
      path: '/aj'
      fullPath: '/aj'
      preLoaderRoute: typeof AjRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjRoute: AjRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
